[workspace]
members = [
    "probe-rs",
    "probe-rs-t2rust",
    "probe-rs-cli-util",
    "cli",
    "gdb-server",
]

[profile.release]
debug = true

[patch.crates-io]
jaylink = { path = "../jaylink" }
