[workspace]
members = [
    "probe-rs",
    "probe-rs-t2rust",
    "probe-rs-cli-util",
    "cli",
    "gdb-server",
]

[patch.crates-io]
jaylink = { git = 'https://github.com/mattico/jaylink', branch = 'usbdk' }
